### PR TITLE
Add Mac OS X p4 command line tool install

### PR DESCRIPTION
**Pull request by Sauraus**

### CODE REVIEW

**Comment by Sauraus** [comment]
Errors do not appear related to my changes.

**Comment by Sauraus** [comment]
@dhoer may need to update the README with details of OS X support. :)

**Comment by dhoer** [comment]
Done, thanks for the PR

**Comment by dhoer** [comment]
v1.4.1 is released to supermarket and macosx branch created to test xcode versions on travis-ci

**Pull request merged**
